import { cookies } from 'next/headers';
import '../globals.css'
import axios from 'axios';
import { useStore } from "@/store/store";
import StoreInitializer from "@/components/StoreInitializer";
import { Sidebar } from '@/components/sidebar/sidebar';

/*export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}*/

async function getTasks() {
    try {
        const cookie = cookies().get('token')?.value;
        const response = await axios.get("http://localhost:5000/api/task", { headers: { cookie }, withCredentials: true });
        return response.data;
    } catch (error: any) {
        return error.response.data;
    }
}

export default async function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {

    const tasks = await getTasks();

    useStore.setState({ tasks: tasks.tasks });
    console.log("Working");

    return (
        <>
            <StoreInitializer tasks={tasks.tasks} />
            <div className='flex'>
                <div className=''>
                    <Sidebar />
                </div>

                <div className=''>
                    {children}
                </div>
            </div>
        </>
    )
}
